version: '3'

tasks:
  setup-macos:
    - DIR=~/.config/alacritty && mkdir -p $DIR
    - FILE=~/.config/alacritty/alacritty.yml && [ ! -d "$FILE" ] || mv $FILE "$FILE.bk"
    - FILE=~/.config/alacritty/alacritty.yml && ln -s $(pwd)/macos/alacritty.yml $FILE

  remove:
    - rm -rf ~/.config/alacritty
