version: '3'

includes:
  generic: ../Taskfile.yaml

tasks:
  setup:
    - task: generic:setup-paths
    - task: install-fonts
    - brew install git git-lfs tmux curl sshuttle ca-certificates gnupg wget
    - task: install-nvim
    - task: install-envman
    # faster tools
    - brew install bat exa ripgrep fd
      # -- zoxide --
    - brew install zoxide
      # -- fzf --
    - DIR=~/.fzf && git -C "$DIR" pull || (git clone --depth=1 https://github.com/junegunn/fzf.git "$DIR" && $DIR/install)
    # development
    - brew install cmake ninja make go python yarn
      # -- nodejs --
    - brew install nvm
    - mkdir -p ~/.nvm
    - \. "/opt/homebrew/opt/nvm/nvm.sh" && nvm install --lts
      # -- bazel --
    - brew install bazel
      # -- k8s and containers --
    - brew install docker docker-compose
    - curl -sS https://webinstall.dev/k9s | bash
      # -- lazygit --
    - go install github.com/jesseduffield/lazygit@latest
      # -- github cli --
    - brew install gh
      # -- gcloud cli --
    - task: install-gcloud-cli
      # -- aws cli --
    - task: install-aws-cli
      # -- help
    - task: generic:install-helm

  install-fonts:
    - brew tap homebrew/cask-fonts
    - brew install --cask font-iosevka-nerd-font font-iosevka

  # envman (2.4.0)
  install-envman:
    - curl -fL https://github.com/bitrise-io/envman/releases/download/2.4.0/envman-"$(uname -s)"-"$(uname -m)" > ~/.local/bin/envman
    - chmod +x ~/.local/bin/envman

  # neovim (stable)
  install-nvim:
    - mkdir -p ~/Lab/apps/nvim && rm -rf ~/Lab/apps/nvim/nvim-macos
    - wget -qO- https://github.com/neovim/neovim/releases/download/stable/nvim-macos.tar.gz | tar xvz -C ~/Lab/apps/nvim
    - ln -sf ~/Lab/apps/nvim/nvim-macos/bin/nvim ~/.local/bin/nvim
    - mkdir -p ~/.vim/sessions

  install-gcloud-cli:
    dir: ~/lab/apps/
    vars:
      file_name: google-cloud-cli-425.0.0-darwin-arm.tar.gz
    cmds:
      - curl -o https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/{{.file_name}}
      - tar -xf {{.file_name}} && rm -rf {{.file_name}}
      - rm -rf gcloud-cli && mv google-cloud-sdk ./gcloud-cli
      - ./gcloud-cli/install.sh --path-update=false --usage-reporting=false --command-completion=false

  install-aws-cli:
    dir: ~/lab/apps/
    vars:
      file_name: AWSCLIV2.pkg
    cmds:
      - curl "https://awscli.amazonaws.com/{{.file_name}}" -o "AWSCLIV2.pkg"
      - sudo installer -pkg ./AWSCLIV2.pkg -target /

  add-ssh-key:
    cmds:
      - ssh-add ~/.ssh/{{.KeyName}}
