version: '3'

includes:
  generic: ../Taskfile.yaml

tasks:
  setup:
    - task: generic:setup-paths
    - task: install-fonts
    - brew install git tmux curl sshuttle ca-certificates gnupg
    - task: install-nvim
    - task: install-envman
    # faster tools
    - brew install bat exa ripgrep fd
      # -- zoxide --
    - brew install zoxide
      # -- fzf --
    - DIR=~/.fzf && git -C "$DIR" pull || (git clone --depth=1 https://github.com/junegunn/fzf.git "$DIR" && $DIR/install)
    # development
    - brew install cmake ninja make go python yarn
      # -- nodejs --
    - brew install nvm
    - mkdir -p ~/.nvm
    - \. "/opt/homebrew/opt/nvm/nvm.sh" && nvm install --lts
      # -- bazel --
    - brew install bazel
      # -- k8s and containers --
    - brew install docker docker-compose
    - curl -sS https://webinstall.dev/k9s | bash
      # -- lazygit --
    - go install github.com/jesseduffield/lazygit@latest
      # -- github cli --
    - brew install gh

  install-fonts:
    - brew tap homebrew/cask-fonts
    - brew install --cask font-iosevka-nerd-font font-iosevka

  # envman (2.4.0)
  install-envman:
    - curl -fL https://github.com/bitrise-io/envman/releases/download/2.4.0/envman-"$(uname -s)"-"$(uname -m)" > ~/.local/bin/envman
    - chmod +x ~/.local/bin/envman

  # neovim (stable)
  install-nvim:
    - mkdir -p ~/Lab/apps/nvim && rm -rf ~/Lab/apps/nvim/nvim-macos
    - wget -qO- https://github.com/neovim/neovim/releases/download/stable/nvim-macos.tar.gz | tar xvz -C ~/Lab/apps/nvim
    - ln -sf ~/Lab/apps/nvim/nvim-macos/bin/nvim ~/.local/bin/nvim
    - mkdir -p ~/.vim/sessions

  add-ssh-key:
    cmds:
      - ssh-add ~/.ssh/{{.KeyName}}
