version: "3"

tasks:
  setup-paths:
    internal: true
    cmds:
      - mkdir -p ~/.local/bin # common place to store in path binaries
      - mkdir -p ~/Lab/apps # common place to store custom apps and their files

  setup-git:
    - git config --global user.name "{{.Name}}"
    - git config --global user.email "{{.Email}}"

  generate-ssh-keys:
    - ssh-keygen -t ed25519 -C "{{.Email}}"

  github-login:
    - gh auth login -h github.com -s admin:public_key

  github-add-ssh-key:
    - gh ssh-key add ~/.ssh/{{.KeyName}}.pub --title "{{.Title}}"
